language: go
go:
  - 1.16.x
matrix:
  include:
    - os: linux
      env: MAKE=make
    - os: osx
      osx_image: xcode11.3
      env: MAKE=make
  fast_finish: true
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
addons:
  apt:
    packages:
      # install 7z on Linux so both the Linux and Windows build can make the zip file the same way
      - p7zip-full
  homebrew:
    packages:
      # install modern bash and coreutils on macOS so that version.sh script works correctly
      - bash
      - coreutils
    update: true
install:
  - make depend
script:
  - make test
  - make build
  # Deploy build result to s3
  - export AWS_ACCESS_KEY_ID=AKIAIX3L4RHHIREAHABQ
  - export AWS_SECRET_ACCESS_KEY=${RSBIN_KEY}
  - "[[ -z $AWS_SECRET_ACCESS_KEY ]] || make upload"
